# 端口
server:
  port: 7081

# Sa-Token 配置
sa-token:
  # SSO-相关配置
  sso:
    # SSO-Server端-单点登录授权地址
    auth-url: http://sso.stp.com:7080/sso/auth
    # SSO-Server端-单点注销地址
    slo-url: http://sso.stp.com:7080/sso/signout

  # 配置 Sa-Token 单独使用的Redis连接 （此处需要和SSO-Server端连接同一个Redis）
  alone-redis:
    # Redis数据库索引
    database: 6
    # Redis服务器地址
    host: 192.168.2.146
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间
    timeout: 10s
